---
name: Sync Fork
on:
  # schedule:
  #   - cron: '*/30 * * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0.9
        with:
          owner: adferrand
          repo: dnsrobocert
          pr_title: Fork Sync
          pr_message: Look at me I'm a fork!
          auto_approve: false
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: master