name: Merge upstream branches
on:
  workflow_dispatch:
  # schedule:
  #    # actually, ~5 minutes is the highest
  #    # effective frequency you will get
  #   - cron:  '* * * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git remote add upstream https://github.com/adferrand/dnsrobocert
          git fetch upstream
          git checkout -b upstream-merge
          git merge --no-edit upstream/master
          git push origin upstream-merge

          # etc