---
  name: Merge upstream branches
  on:
    workflow_dispatch:
    # schedule:
    #    # actually, ~5 minutes is the highest
    #    # effective frequency you will get
    #   - cron:  '* * * * *'
  jobs:
    merge:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            token: ${{ secrets.ACTIONS_TOKEN }}
            fetch-depth: 0
        - name: Merge upstream
          run: |
            git remote add upstream https://github.com/adferrand/dnsrobocert
            git fetch upstream
            git merge --no-edit upstream/master
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v6