---
  name: Sync Fork with Upstream
  on:
    workflow_dispatch:
    schedule:
      # 12:00 UTC on Tuesdays
      - cron:  '0 0 * * 2'
  
  env:
    UPSTREAM_REPO: adferrand/dnsrobocert
    ORG_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
    GIT_EMAIL: systems@ycharts.com
    GIT_NAME: ychartsdeployer
    GITHUB_TEAM: DevOps

  jobs:
    merge:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout fork
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.ACTIONS_TOKEN }}

        - name: Fetch upstream changes - master
          run: |
            git config --global user.email ${{ env.GIT_EMAIL }}
            git config --global user.name ${{ env.GIT_NAME }}
            git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}
            git fetch upstream master:upstream-master
            git reset --hard upstream-master

        - name: Create Pull Request - master
          uses: peter-evans/create-pull-request@v6
          with:
            token: ${{ env.ORG_TOKEN }}
            branch: upstream-sync
            base: master
            title: Sync with upstream

        - name: Fetch upstream changes - legacy
          run: |
            git fetch upstream legacy:upstream-legacy
            git reset --hard upstream-legacy

        - name: Create Pull Request - legacy
          uses: peter-evans/create-pull-request@v6
          with:
            token: ${{ env.ORG_TOKEN }}
            branch: upstream-sync-legacy
            base: legacy
            title: Sync with upstream
